newline_style = "Unix"
edition = "2021"
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true
max_width = 74

# unstable
combine_control_expr = false
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
imports_granularity = "Crate"
#normalize_comments = true
normalize_doc_attributes = true
group_imports = "StdExternalCrate"
